/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package csc;

import java.awt.Color;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author munachianya
 */
public class cbt extends javax.swing.JFrame {

    String questions[] = {
        "What is the chemical symbol for water?",
        "What is the capital of France?",
        "Which planet is known as the Red Planet?",
        "In which year did Nigeria gain independence from British rule?",
        "What is the largest organ in the human body?",
        "What is the square root of 144?",
        "Which gas do plants absorb from the atmosphere?",
        "Which African country is known as the 'Giant of Africa'?",
        "Who is the author of 'To Kill a Mockingbird'?",
        "What is the tallest mountain in the world?",
        "What is the atomic number of carbon?",
        "Which continent is home to the Sahara Desert?",
        "What is the capital of Japan?",
        "Who is the first President of the United States?",
        "What is the freezing point of water in Celsius?",
        "What is the chemical formula for table salt?",
        "Which gas is responsible for the Earth's ozone layer?",
        "Who is the current President of Nigeria?",
        "What is the formula for the area of a rectangle?",
        "Who is the father of modern physics?"
    };

    String optionA[] = {
        "H2O", "Berlin", "Mars", "1956", "Heart", "12", "Oxygen", "Nigeria", "Harper Lee", "Mount Kilimanjaro",
        "6", "Africa", "Tokyo", "George Washington", "0°C", "NaCl", "Oxygen", "Muhammadu Buhari", "Length x Width", "Isaac Newton"};

    String optionB[] = {
        "CO2", "Madrid", "Venus", "1960", "Lung", "11", "Carbon Dioxide", "South Africa", "J.K. Rowling", "Mount Everest",
        "14", "Asia", "Seoul", "Thomas Jefferson", "100°C", "H2SO4", "Nitrogen", "Olusegun Obasanjo", "Width x Height", "Albert Einstein"};

    String optionC[] = {
        "N2", "Rome", "Jupiter", "1963", "Liver", "10", "Nitrogen", "Ghana", "Harper Lee", "Mount Fuji",
        "7", "Australia", "Beijing", "Benjamin Franklin", "32°F", "CH4", "Carbon Dioxide", "Goodluck Jonathan", "Length x Length", "Niels Bohr"};

    String optionD[] = {
        "CH4", "Paris", "Saturn", "1961", "Skin", "9", "Hydrogen", "Egypt", "F. Scott Fitzgerald", "K2",
        "12", "Europe", "London", "Abraham Lincoln", "273.15K", "C6H12O6", "Oxygen", "Nnamdi Azikiwe", "Width x Width", "Richard Feynman"};

    String Answer[] = {
        "H2O", "Paris", "Mars", "1960", "Skin", "12", "Carbon Dioxide", "Nigeria", "Harper Lee", "Mount Everest",
        "6", "Africa", "Tokyo", "George Washington", "0°C", "NaCl", "Oxygen", "Muhammadu Buhari", "Length x Width", "Albert Einstein"};

    String YourAnswer[] = {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""};

    int i = 0;
    int CorrectAnswer = 0;

    /**
     * Creates new form _
     */
    public cbt() {
        initComponents();
        jTextArea1.setText(questions[i]);
        jRadioButton1.setText(optionA[i]);
        jRadioButton2.setText(optionB[i]);
        jRadioButton3.setText(optionC[i]);
        jRadioButton4.setText(optionD[i]);
        jLabel2.setText("Question" + (i + 1));
        time t = new time();
        Thread t1 = new Thread(t);
        t1.start();
        
        blink b = new blink();
        Thread b1 = new Thread(b);
        b1.start();

        if (i == 0) {
            jButton2.setEnabled(false);
        } else {
            jButton2.setEnabled(true);
        }
    }

    // Load the user's previous answer for this question
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.__
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 113));

        jLabel1.setFont(new java.awt.Font("Phosphate", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Computer Based Test");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Luminari", 1, 16)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("jRadioButton1");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("jRadioButton1");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("jRadioButton1");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jButton1.setText("Next ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jButton2.setText("Previous");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel2");

        jButton4.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jButton4.setText("Calculator 🧮");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        timeLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(98, 98, 98)
                                .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(135, 135, 135)
                                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(226, 226, 226)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(79, 79, 79)
                                        .addComponent(jButton4)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int lastQuestion = questions.length;
        if (YourAnswer[i] == Answer[i]) {
            ++CorrectAnswer;
        }

        if (i == lastQuestion - 1) {
            JOptionPane.showMessageDialog(rootPane, "This is the last question");
        } else {

            ++i;
            jTextArea1.setText(questions[i]);
            jRadioButton1.setText(optionA[i]);
            jRadioButton2.setText(optionB[i]);
            jRadioButton3.setText(optionC[i]);
            jRadioButton4.setText(optionD[i]);
            String previousAnswer = YourAnswer[i];
            if (previousAnswer.equals(jRadioButton1.getText())) {
                jRadioButton1.setSelected(true);
            } else if (previousAnswer.equals(jRadioButton2.getText())) {
                jRadioButton2.setSelected(true);
            } else if (previousAnswer.equals(jRadioButton3.getText())) {
                jRadioButton3.setSelected(true);
            } else if (previousAnswer.equals(jRadioButton4.getText())) {
                jRadioButton4.setSelected(true);
            } else {
                buttonGroup1.clearSelection();
            }
            jLabel2.setText("Question " + (i + 1));

            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
        }

        // TODO add your handling code here:______
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (i == 0) {
            JOptionPane.showMessageDialog(rootPane, "This is the first question");
        } else {
            --i;
            jTextArea1.setText(questions[i]);
            jRadioButton1.setText(optionA[i]);
            jRadioButton2.setText(optionB[i]);
            jRadioButton3.setText(optionC[i]);
            jRadioButton4.setText(optionD[i]);
            jLabel2.setText("Question" + (i + 1));
            jButton3.setEnabled(true);

            String previousAnswer = YourAnswer[i];
            if (previousAnswer.equals(jRadioButton1.getText())) {
                jRadioButton1.setSelected(true);
            } else if (previousAnswer.equals(jRadioButton2.getText())) {
                jRadioButton2.setSelected(true);
            } else if (previousAnswer.equals(jRadioButton3.getText())) {
                jRadioButton3.setSelected(true);
            } else if (previousAnswer.equals(jRadioButton4.getText())) {
                jRadioButton4.setSelected(true);
            } else {
                buttonGroup1.clearSelection();
            }
        }
        // TODO add your handling code here:_____
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int lastQuestion = questions.length;
        boolean unansweredFound = false;
        StringBuilder unansweredQuestionsMessage = new StringBuilder();

        if (i == lastQuestion - 1) {
            // Check for unanswered questions and collect the indices._
            for (int a = 0; a < questions.length; a++) {
                if (YourAnswer[a] == Answer[a]) {
                    ++CorrectAnswer;
                } else if (YourAnswer[a].isEmpty()) {
                    unansweredFound = true;
                    unansweredQuestionsMessage.append("Question " + a + 1 + " :").append("\n");
                }
            }
            if (unansweredFound) {
                JOptionPane.showMessageDialog(rootPane, "You didn't answer the following questions:\n" + unansweredQuestionsMessage.toString());
            }
            JOptionPane.showMessageDialog(rootPane, "This is the last question \n You scored " + CorrectAnswer + " out of " + questions.length);
            jButton3.setEnabled(false);
        } else {
            ++i;
            jTextArea1.setText(questions[i]);
            jRadioButton1.setText(optionA[i]);
            jRadioButton2.setText(optionB[i]);
            jRadioButton3.setText(optionC[i]);
            jRadioButton4.setText(optionD[i]);
            jLabel2.setText("Question" + i);
            buttonGroup1.clearSelection();

            jButton2.setEnabled(true);

        }
        // TODO add your handling code here:__
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if (jRadioButton1.isSelected()) {
            YourAnswer[i] = jRadioButton1.getText();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if (jRadioButton2.isSelected()) {
            YourAnswer[i] = jRadioButton2.getText();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        if (jRadioButton3.isSelected()) {
            YourAnswer[i] = jRadioButton3.getText();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        if (jRadioButton4.isSelected()) {
            YourAnswer[i] = jRadioButton4.getText();
        }
        // TODO add your handling code here:__
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Runtime.getRuntime().exec("open -a Calculator");
        } catch (Exception e) {
        }
// TODO add your handling code here:__
    }//GEN-LAST:event_jButton4ActionPerformed

    public class time implements Runnable {

        /**
         *
         */
        @Override
        public void run() {
            try {
                for (int i = 1; i < 2; i--) {
                    Date date = new Date();
                    timeLabel.setText(date.toString());
                    TimeUnit.SECONDS.sleep(1);
                }
            } catch (Exception e) {
                System.out.println("error");
            }

        }

    }

    public class blink implements Runnable {

        /**
         *
         */
        @Override
        public void run() {
            try {
                for (int i = 1; i < 2; i--) {

                    timeLabel.setForeground(Color.red);
                    TimeUnit.SECONDS.sleep(1);
                    timeLabel.setForeground(Color.white);
                    TimeUnit.SECONDS.sleep(1);
                    timeLabel.setForeground(Color.red);
                    TimeUnit.SECONDS.sleep(1);
                    timeLabel.setForeground(Color.white);
                    TimeUnit.SECONDS.sleep(1);
                    timeLabel.setForeground(Color.green);
                    TimeUnit.SECONDS.sleep(1);
                }
            } catch (Exception e) {
                System.out.println("error");
            }

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cbt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cbt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cbt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cbt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cbt().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
